### ISSUE TITLE
Realtek Audio Driver

### ISSUE THREAD

**Issue by ikrananka** [distantorigin/XPS-Enhancements#6] opened 2018-10-14 20:37 UTC
I saw that you just changed your recommendation for how to eliminate Waves MaxxAudioPro, i.e. by switching the audio driver to the generic Microsoft HD Audio Driver.  Couple of problems with this:

1.  You still say in the introductory text that using the generic Microsoft HD Audio Driver "will produce crackling and popping under certain conditions".  Yet at the end of the section you now say "Enjoy your crystal-clear audio experience." with this same generic driver.  I'm guessing one or the other is true but not both.

2.  More importantly, I have found it impossible to get my system to stay on the generic Microsoft HD Audio Driver.  Firstly, when the Realtek driver is removed and the MS generic driver installed Device Manager shows an unknown device "Detection Verification".  Secondly, Windows Update just reinstalls the Realtek driver including Waves MaxxAudioPro.  I have found no way to get my XPS 13 9370 to stay on the generic MS driver while connected to the internet and Windows Update is active.  I know that it is possible to disable Windows Update from updating ALL device drivers but not just a specific one.  Have you had this issue?  Might be worth updating your text if this is a common issue.  Would love to know your experience with this.

**Comment by miinht** [comment] 2018-10-16 04:05
I also agree with the above comment/issues. The updated guide on how to remove MaxxAudio is insufficient as it leaves you with generic Windows drivers that DO NOT function properly. Audio crackling, drivers issues, etc. 


Here's a GitHub link to a prerelease version of an updated KSMRD modded driver the original developer is working on. Confirmed working with the latest Windows update.

https://github.com/kevinshroff/KSMRD-Modded-Realtek-Audio-Drivers

**Comment by Freakston** [comment] 2018-10-16 04:10
@itsminht If the above drivers work then you can update readme.md by creating a pull request with the latest link.

**Comment by distantorigin** [comment] 2018-10-16 17:49
Hello!

Thanks for bringing this to my attention. Heavy revisions coming soon. Sorry for the confusion and disservice of having mismatched information.

I've been able to maintain the Windows 10 (1809) generic HD audio without crackling, but I recognize this is not the case for everyone. I was also unaware of this GitHub link.

I'll update this issue once the changes are posted.

**Comment by distantorigin** [comment] 2018-10-17 00:18
I've revised the Audio section. Hopefully this covers the content of this issue nicely. If no negative comments are posted here in the next day, I'll consider this issue closed. The new document is in master now.

**Comment by miinht** [comment] 2018-10-17 07:33
@distantorigin In regards to the generic HD audio drivers from Microsoft, how are they in terms of sound quality and functionality? Are you able to use an external microphone when it's plugged into the laptop and has there been any issues where Windows Update automatically downloads the Dell Audio drivers back again. Lastly, has there been any audio crackling or issues with the generic drivers? Also which laptop are you using them with? XPS 9370? And is the Windows 10 (1809) you are running on the latest Windows October update, correct?

**Comment by distantorigin** [comment] 2018-10-17 09:00
@itsminht Windows Update has not replaced the Generic HD Audio drivers with a faulty version. External mics via the 3.5mm jack do not work, and there is no prompt to "Pick a device."

I receive no crackling or random other oral artifacts during sound playback, and in fact, compared to the Realtek driver, my internal microphone sounds markedly better. I recognize this is not the case for everyone, though. It's also worth noting that I'm no audio producer, so the driver may very well produce a great deal of crackling when using those types of applications via ASIO.

I'm running Windows 10 Version 1809 (OS Build 17763.550, which is the latest mainline version (not Insider)) on a Dell XPS 13 9370 consumer model.

**Comment by ikrananka** [comment] 2018-10-17 13:38
@distantorigin Thanks for addressing this.  No matter what I did I couldn't stop Windows Update from replacing the MS generic HD driver with the Realtek + Waves driver.  I've left this installed for now until the driver from Kevin has settled.  I'd rather his base driver was the latest but it would seem not.  Plus what happens in the future when Realtek/Dell release newer drivers that fix real issues and Kevin doesn't update his driver?

**Comment by distantorigin** [comment] 2018-10-17 16:27
@ikrananka I'm currently on the HD Audio as well, though I will likely be reverting on a permanent basis to Waves Audio because of a few issues that I'm having. Not anything crackling related.

It is very likely that someone would be able to pick up where Kevin left off if he stops maintaining the driver, though I understand the concern.

I'm closing this issue, as the problems presented seem to be resolved.

**Closed as completed by distantorigin** 2018-10-17 16:27 UTC
